name: CI
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - working-directory: ./hoekstraenveldhuis.nl
      - name: Install modules
        run: yarn
      - name: Lint using ESLint
        run: yarn run eslint .
