name: Lint
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        working-directory: /hoekstraenveldhuis.nl
        run: yarn
      - name: Lint using ESLint
        working-directory: /hoekstraenveldhuis.nl
        run: yarn run eslint .
